import jsPDF from "jspdf";
import autoTable from "jspdf-autotable";
import { Scheme } from "@/data/schemes";

export const generateSchemePDF = (scheme: Scheme) => {
  const doc = new jsPDF();

  // Add Title
  doc.setFontSize(20);
  doc.setTextColor(40);
  doc.text("Government Scheme Details", 105, 15, { align: "center" });

  // Add Scheme Name
  doc.setFontSize(16);
  doc.setTextColor(0, 102, 204);
  doc.text(scheme.name, 10, 30);

  // Add Content Table
  autoTable(doc, {
    startY: 40,
    head: [["Field", "Details"]],
    body: [
      ["Category", scheme.category],
      ["Description", scheme.description],
      ["Benefits", scheme.benefits],
      ["Documents Required", scheme.documents.join(", ")],
      ["Application Link", scheme.applyUrl],
    ],
    theme: "striped",
    headStyles: { fillColor: [0, 102, 204] },
    columnStyles: {
      0: { fontStyle: "bold", cellWidth: 40 },
      1: { cellWidth: 140 },
    },
  });

  // Footer
  const pageCount = (doc as any).internal.getNumberOfPages();
  for (let i = 1; i <= pageCount; i++) {
    doc.setPage(i);
    doc.setFontSize(10);
    doc.setTextColor(150);
    doc.text(
      "Generated by BHARATSeva AI - " + new Date().toLocaleDateString(),
      105,
      doc.internal.pageSize.height - 10,
      { align: "center" }
    );
  }

  return doc.output("blob");
};

export const generateApplicationPDF = (data: any) => {
  const doc = new jsPDF();

  // Add Header
  doc.setFontSize(20);
  doc.setTextColor(40);
  doc.text("BHARATSeva AI - Application Form", 105, 15, { align: "center" });

  // Add Ref Number
  doc.setFontSize(14);
  doc.setTextColor(100);
  doc.text(`Reference No: ${data.ref}`, 105, 25, { align: "center" });

  // Add Application Data
  autoTable(doc, {
    startY: 35,
    head: [["Field", "Information"]],
    body: [
      ["Applicant Name", data.name || "N/A"],
      ["Age", data.age || "N/A"],
      ["Contact Number", data.phone || "N/A"],
      ["State", data.state || "N/A"],
      ["Application Date", data.date || new Date().toLocaleDateString()],
      ["Status", "Submitted Successfully"],
    ],
    theme: "striped",
    headStyles: { fillColor: [0, 102, 204] },
    columnStyles: {
      0: { fontStyle: "bold", cellWidth: 50 },
      1: { cellWidth: 130 },
    },
  });

  // Footer
  const pageCount = (doc as any).internal.getNumberOfPages();
  for (let i = 1; i <= pageCount; i++) {
    doc.setPage(i);
    doc.setFontSize(10);
    doc.setTextColor(150);
    doc.text(
      "BHARATSeva AI - Empowering Citizens",
      105,
      doc.internal.pageSize.height - 10,
      { align: "center" }
    );
  }

  doc.save(`Application_${data.ref}.pdf`);
  return doc.output("blob");
};

export const shareOnWhatsApp = (scheme: Scheme) => {
  const message = `*Government Scheme Information*\n\n*Name:* ${scheme.name}\n*Category:* ${scheme.category}\n*Benefits:* ${scheme.benefits}\n*Learn More:* ${scheme.applyUrl}\n\nGenerated via BHARATSeva AI`;
  const whatsappUrl = `https://wa.me/?text=${encodeURIComponent(message)}`;
  window.open(whatsappUrl, "_blank");
};
